In [7]:
import sklearn
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data[:, [2, 3]]
X[:10]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1]])

In [8]:
Y = iris.target
Y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)
X_train[:10]

array([[3.5, 1. ],
       [5.5, 1.8],
       [5.7, 2.5],
       [5. , 1.5],
       [5.8, 1.8],
       [3.9, 1.1],
       [6.1, 2.3],
       [4.7, 1.6],
       [3.8, 1.1],
       [4.9, 1.8]])

In [13]:
X_test[:10]

array([[5.1, 2.4],
       [4. , 1. ],
       [1.4, 0.2],
       [6.3, 1.8],
       [1.5, 0.2],
       [6. , 2.5],
       [1.3, 0.3],
       [4.7, 1.5],
       [4.8, 1.4],
       [4. , 1.3]])

In [14]:
Y_train[:10]

array([1, 2, 2, 2, 2, 1, 2, 1, 1, 2])

In [15]:
Y_test[:10]

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1])

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
X_train_std[:10]

array([[-0.18295039, -0.29318114],
       [ 0.93066067,  0.7372463 ],
       [ 1.04202177,  1.63887031],
       [ 0.6522579 ,  0.35083601],
       [ 1.09770233,  0.7372463 ],
       [ 0.03977182, -0.16437771],
       [ 1.26474398,  1.38126345],
       [ 0.48521625,  0.47963944],
       [-0.01590873, -0.16437771],
       [ 0.59657735,  0.7372463 ]])

In [17]:
X_test_std[:10]

array([[ 0.70793846,  1.51006688],
       [ 0.09545238, -0.29318114],
       [-1.35224199, -1.32360858],
       [ 1.37610509,  0.7372463 ],
       [-1.29656144, -1.32360858],
       [ 1.20906343,  1.63887031],
       [-1.40792255, -1.19480515],
       [ 0.48521625,  0.35083601],
       [ 0.5408968 ,  0.22203258],
       [ 0.09545238,  0.09322915]])